import type { ContentTemplate } from '@/types/generation';

export const CONTENT_TEMPLATES: ContentTemplate[] = [
  {
    id: 'linkedin-thought-leadership',
    name: 'LinkedIn Thought Leadership',
    description: 'A professional insight post that positions you as an industry expert',
    contentType: 'social_linkedin',
    icon: '💼',
    promptScaffold: 'Write a LinkedIn thought leadership post. Start with a bold, contrarian, or insightful opening hook. Share a personal observation or experience. Provide 3 actionable insights. End with a question to spark engagement. Use short paragraphs with line breaks for LinkedIn readability.',
    formDefaults: { lengthPreference: 'medium' },
  },
  {
    id: 'instagram-caption',
    name: 'Instagram Caption',
    description: 'An engaging caption with a hook, story, and call to action',
    contentType: 'social_instagram',
    icon: '📸',
    promptScaffold: 'Write an Instagram caption. Start with a compelling 1-2 line hook (the part visible before "more"). Tell a brief story or share value. End with a clear CTA. Add a line break then 5-10 relevant hashtags.',
    formDefaults: { lengthPreference: 'short' },
  },
  {
    id: 'twitter-thread',
    name: 'Twitter/X Thread',
    description: 'A punchy thread with 5-8 numbered tweets',
    contentType: 'social_twitter',
    icon: '🐦',
    promptScaffold: 'Write a Twitter/X thread of 6-8 tweets. Tweet 1: bold hook that makes people want to read more. Tweets 2-7: one insight per tweet, numbered (2/, 3/, etc.). Last tweet: summary + CTA + ask for retweet. Keep each tweet under 280 characters.',
    formDefaults: { lengthPreference: 'medium' },
  },
  {
    id: 'blog-post-longform',
    name: 'Blog Post (Long-form)',
    description: 'A comprehensive article with intro, sections, and conclusion',
    contentType: 'blog_post',
    icon: '📝',
    promptScaffold: 'Write a long-form blog post. Include: SEO-optimized title, compelling intro (hook + what reader will learn), 3-4 H2 sections with H3 subpoints, actionable takeaways, and a conclusion with CTA.',
    formDefaults: { lengthPreference: 'long' },
  },
  {
    id: 'blog-listicle',
    name: 'Blog Listicle',
    description: 'A numbered tips article that\'s easy to scan and share',
    contentType: 'blog_listicle',
    icon: '📋',
    promptScaffold: 'Write a listicle blog post with 7-10 numbered tips or items. Include a catchy title (e.g., "X Ways to..."), brief intro, numbered sections each with a subheading, 2-3 sentences of explanation, and a wrap-up paragraph.',
    formDefaults: { lengthPreference: 'medium' },
  },
  {
    id: 'email-newsletter',
    name: 'Email Newsletter',
    description: 'A newsletter with subject line, preview text, and 3 sections',
    contentType: 'email_newsletter',
    icon: '📧',
    promptScaffold: 'Write an email newsletter. Include: 3 subject line options, preview text (40 chars), greeting, 3 content sections (each with a subheading and 2-3 short paragraphs), and a CTA button with text.',
    formDefaults: { lengthPreference: 'medium' },
  },
  {
    id: 'email-subjects',
    name: 'Email Subject Lines',
    description: '10 subject line variants with A/B testing categories',
    contentType: 'email_subjects',
    icon: '✉️',
    promptScaffold: 'Generate 10 email subject lines. Group them into categories: Curiosity (2), Benefit-driven (2), Question-based (2), Urgency (2), Personal (2). Keep each under 50 characters. Include preview text for each.',
    formDefaults: { lengthPreference: 'short' },
  },
  {
    id: 'youtube-script',
    name: 'YouTube Video Script',
    description: 'A full video script with hook, content structure, and CTA',
    contentType: 'video_script_youtube',
    icon: '🎬',
    promptScaffold: 'Write a YouTube video script. Structure: Hook (0-30s, grab attention immediately), Intro (30-60s, who you are + what they\'ll learn), Main Content (3 sections with timestamps), and Outro (last 60s with CTA to subscribe, watch next video, join community).',
    formDefaults: { lengthPreference: 'long' },
  },
  {
    id: 'tiktok-script',
    name: 'TikTok/Reels Script',
    description: 'A fast-paced 60-second script designed for short-form video',
    contentType: 'video_script_tiktok',
    icon: '🎵',
    promptScaffold: 'Write a TikTok/Reels script for a 60-second video. Include: a 3-second text hook (on-screen), a punchy spoken hook (first 5 seconds), the core content in 3-4 short punchy segments, and an ending that prompts a follow or comment. Include stage directions.',
    formDefaults: { lengthPreference: 'short' },
  },
  {
    id: 'google-ad-copy',
    name: 'Google Ad Copy',
    description: 'Headlines and descriptions for a high-converting Google ad',
    contentType: 'ad_copy',
    icon: '🎯',
    promptScaffold: 'Write Google Search Ad copy. Provide: 5 headlines (max 30 chars each), 3 long headlines (max 90 chars each), 4 descriptions (max 90 chars each). Focus on benefits, include a CTA, use the keyword naturally.',
    formDefaults: { lengthPreference: 'short' },
  },
  {
    id: 'product-description',
    name: 'Product Description',
    description: 'A benefit-driven product description that converts',
    contentType: 'product_description',
    icon: '🛍️',
    promptScaffold: 'Write a product description. Include: an attention-grabbing headline, a 2-3 sentence emotional lead (the transformation the product enables), 3-5 bullet point features framed as benefits, technical specs section, and a closing sentence that reinforces the main value.',
    formDefaults: { lengthPreference: 'medium' },
  },
  {
    id: 'press-release',
    name: 'Press Release',
    description: 'A standard PR-format press release with quotes',
    contentType: 'press_release',
    icon: '📰',
    promptScaffold: 'Write a press release in standard AP style. Include: FOR IMMEDIATE RELEASE header, city/date dateline, headline, subheadline, 3 body paragraphs (who/what/when/where/why, details, context), one quote from a company spokesperson, boilerplate "About" section, and ### ending.',
    formDefaults: { lengthPreference: 'long' },
  },
];

export const CONTENT_TYPE_LABELS: Record<string, string> = {
  blog_post: 'Blog Post',
  blog_listicle: 'Blog Listicle',
  social_instagram: 'Instagram',
  social_linkedin: 'LinkedIn',
  social_twitter: 'Twitter/X Thread',
  email_newsletter: 'Email Newsletter',
  email_subjects: 'Email Subjects',
  video_script_youtube: 'YouTube Script',
  video_script_tiktok: 'TikTok/Reels Script',
  ad_copy: 'Ad Copy',
  product_description: 'Product Description',
  press_release: 'Press Release',
};
